name: API and Web Automation Workflow


# EVENT
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Manually running a workflow  
  workflow_dispatch:

jobs:
  run-automation-test:
    # Running on Virtual machine
    runs-on: ubuntu-latest


    steps:
    # download repo
    - uses: actions/checkout@v4

    # set up java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    #set up gradlew
    - name: Setup gradlew
      run: chmod +x gradlew
      
    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew SauceDemo

    # Upload Artifact Report
    - name: Archive Test Result
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Cucumber Report
        path: reports

        
   # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
       PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
       PUBLISH_DIR: reports
